let shopItemData = [
    {
        id: "scndn",
        name: "Casual shirt",
        price: 15,
        desc: "Hi-five cotton shirt for sale, high quality shirt",
        img: "images/download.jpg",
    },
    {
        id: "ckjncia",
        name: "Donati gym bottle",
        price: 10,
        desc: "Donati Gym bottle 1ltr, blue&pink colored",
        img: "images/bottle.jpg"
    },
    {
        id: "anuiand",
        name: "H&M T-shirt",
        price: 25,
        desc: "H&M cotton t-shirt for sale, high quality white color.",
        img: "images/images.jpg",
    },
    {
        id: "ffsfsfs",
        name: "Cutlery set of 4",
        price: 12,
        desc: "Hi-five cotton shirt for sale, high quality shirt",
        img: "images/cutlery.jpg",
    },
    {
        id: "thyfhcbcv",
        name: "Mens Suit",
        price: 300,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-4.jpg",
    },
    {
        id: "thiecbawdjksadjk",
        name: "Mens Tie",
        price: 25,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-5.png",
    },
    {
        id: "iuertrywebncdjksadjk",
        name: "Casual shoes",
        price: 200,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-6.png",
    },
    {
        id: "thierytbvcbvzdhadjk",
        name: "black suit",
        price: 450,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-7.png",
    },
    {
        id: "trfoiwfcnbcawdjksadjk",
        name: "polo shirt",
        price: 45,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-8.png",
    },
    {
        id: "cbvxbcvsceldk",
        name: "denim shirt",
        price: 85,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-9.png",
    },
    {
        id: "oiopijmjkhuihb",
        name: "denim pants",
        price: 120,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-10.png",
    },
    {
        id: "rtytytuyuytyytbvncv",
        name: "leather boots",
        price: 350,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-12.png",
    },
]